huds_refresh_interval_ticks: 15
huds_high_frequency_refresh_interval_ticks: 1
legacy_1_18_and_lower_textures: false
money:
  enabled: true
  offset: 91
  # All money playerholders: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#vault
  text: "%vault_eco_balance_formatted%"
  worlds:
    - world
    - world_nether
    - world_the_end
mobcoins:
  enabled: true
  offset: 101
  # All money playerholders: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#vault
  text: "%vault_eco_balance_formatted%"
  worlds:
    - world
    - world_nether
    - world_the_end
minecoins:
  enabled: true
  offset: 111
  # All money playerholders: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#vault
  text: "%vault_eco_balance_formatted%"
  worlds:
    - world
    - world_nether
    - world_the_end
farmcoins:
  enabled: true
  offset: 121
  # All money playerholders: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#vault
  text: "%vault_eco_balance_formatted%"
  worlds:
    - world
    - world_nether
    - world_the_end
jobs_hunter:
    enabled: true
    offset: 151
    # All money playerholders: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#vault
    text: "%vault_eco_balance_formatted%"
    worlds:
      - world
      - world_nether
      - world_the_end
jobs_miner:
  enabled: true
  offset: 161
  # All money playerholders: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#vault
  text: "%vault_eco_balance_formatted%"
  worlds:
    - world
    - world_nether
    - world_the_end
jobs_farmer:
  enabled: true
  offset: 181
  # All money playerholders: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#vault
  text: "%vault_eco_balance_formatted%"
  worlds:
    - world
    - world_nether
    - world_the_end

lang:
  hud_not_found: "&6Hud not found!"
  wrong_usage: "&cWrong command usage."
  destination_set: "&aDestination set."
  destination_removed: "&7Destination removed."
log:
  debug: false
