name: Playerhuds
version: 1.2.0-r2
main: dev.lone.rpghuds.Main
api-version: 1.13
depend:
  - ItemsAdder
  - PlaceholderAPI
  - Vault
commands:
  rpgcompass:
    description: Custom compass command.
    usage: /rpgcompass <player> <set|remove> <world> <x> <y> <z>
  rpghuds:
    description: Main plugin command.
    usage: /rpghuds <action> <hud> [user]
permissions:
  rpghuds.reload:
    description: Permission to use the command /rpghuds reload to reload the plugin.
  rpghuds.show:
    description: Permission to use the command /rpghuds show <hud> on themselves.
  rpghuds.hide:
    description: Permission to use the command /rpghuds hide <hud> on themselves.
  rpghuds.show.others:
    description: Permission to use the command /rpghuds hide <hud> <player> on other players.
  rpghuds.hide.others:
    description: Permission to use the command /rpghuds hide <hud> <player> on other players.
  rpghuds.compass.set:
    description: Permission to use the command /rpgcompass set on themselves.
  rpghuds.compass.remove:
    description: Permission to use the command /rpgcompass remove on themselves.
  rpghuds.compass.set.others:
    description: Permission to use the command /rpgcompass set on other players.
  rpghuds.compass.remove.others:
    description: Permission to use the command /rpgcompass remove on other players.