info:
  namespace: rpghuds
huds:
  money:
    enabled: true
    show:
      auto: false
      underwater: false
    type: CUSTOM
  mobcoins:
    enabled: true
    show:
      auto: false
      underwater: false
    type: CUSTOM
  minecoins:
    enabled: true
    show:
      auto: false
      underwater: false
    type: CUSTOM
  farmcoins:
    enabled: true
    show:
      auto: false
      underwater: false
    type: CUSTOM
  jobs_hunter:
    enabled: true
    show:
      auto: false
      underwater: false
    type: CUSTOM
  jobs_miner:
    enabled: true
    show:
      auto: false
      underwater: false
    type: CUSTOM
  jobs_farmer:
    enabled: true
    show:
      auto: false
      underwater: false
    type: CUSTOM
